kind: pipeline
name: publish

steps:
- name: docker-dev
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: shouptech/nextcloud-news-updater
    tags:
    - ${DRONE_BUILD_NUMBER}
  when:
    event:
      exclude:
      - pull_request

- name: docker-latest
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: shouptech/nextcloud-news-updater
    tags:
    - latest
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: docker-release
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: shouptech/nextcloud-news-updater
    auto_tag: true
  when:
    event:
    - tag
